config/routes.rb
Rails.application.routes.draw do
  
  resources :test_answers
  devise_for :users
  resources :dominos
  get "welcome/domino"
  get "welcome/contactos"
  get "welcome/test"
  root "welcome#index"




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/domino.rb
class Domino < ApplicationRecord
end

app/models/test_answer.rb
class TestAnswer < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
  validates :email, :password, presence: true
  validates :password, length: {minimum:6, maximum:15}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :load_domino


    def load_domino
        @dominos = Domino.all
    end
end

app/controllers/dominos_controller.rb
class DominosController < ApplicationController
  before_action :set_domino, only: [:show, :edit, :update, :destroy]

  # GET /dominos
  # GET /dominos.json
  def index
    @dominos = Domino.all
  end

  # GET /dominos/1
  # GET /dominos/1.json
  def show
  end

  # GET /dominos/new
  def new
    @domino = Domino.new
  end

  # GET /dominos/1/edit
  def edit
  end

  # POST /dominos
  # POST /dominos.json
  def create
    @domino = Domino.new(domino_params)

    respond_to do |format|
      if @domino.save
        format.html { redirect_to @domino, notice: 'Domino was successfully created.' }
        format.json { render :show, status: :created, location: @domino }
      else
        format.html { render :new }
        format.json { render json: @domino.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dominos/1
  # PATCH/PUT /dominos/1.json
  def update
    respond_to do |format|
      if @domino.update(domino_params)
        format.html { redirect_to @domino, notice: 'Domino was successfully updated.' }
        format.json { render :show, status: :ok, location: @domino }
      else
        format.html { render :edit }
        format.json { render json: @domino.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dominos/1
  # DELETE /dominos/1.json
  def destroy
    @domino.destroy
    respond_to do |format|
      format.html { redirect_to dominos_url, notice: 'Domino was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_domino
      @domino = Domino.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def domino_params
      params.require(:domino).permit(:instruction, :question, :answer1, :answer2)
    end
end

app/controllers/test_answers_controller.rb
class TestAnswersController < ApplicationController
  before_action :set_test_answer, only: [:show, :edit, :update, :destroy]

  # GET /test_answers
  # GET /test_answers.json
  def index
    @test_answers = TestAnswer.all
  end

  # GET /test_answers/1
  # GET /test_answers/1.json
  def show
  end

  # GET /test_answers/new
  def new
    @test_answer = TestAnswer.new
  end

  # GET /test_answers/1/edit
  def edit
  end

  # POST /test_answers
  # POST /test_answers.json
  def create
    #@test_answer = TestAnswer.find(test_answer_params)
    #@domino = @test_answer.dominos.new(test_answer_params)

    @test_answer = TestAnswer.new(test_answer_params)
    
    #@article = Article.find(params[:article_id])
    #@comment = @article.comments.create(comment_params)
    #domino = Domino.find(params[:test_answer][:domino_id])

    respond_to do |format|
      if @test_answer.save
        format.html { redirect_to @test_answer, notice: 'Test answer was successfully created.' }
        format.json { render :show, status: :created, location: @test_answer }
      else
        format.html { render :new }
        format.json { render json: @test_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /test_answers/1
  # PATCH/PUT /test_answers/1.json
  def update
    respond_to do |format|
      if @test_answer.update(test_answer_params)
        format.html { redirect_to @test_answer, notice: 'Test answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @test_answer }
      else
        format.html { render :edit }
        format.json { render json: @test_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /test_answers/1
  # DELETE /test_answers/1.json
  def destroy
    @test_answer.destroy
    respond_to do |format|
      format.html { redirect_to test_answers_url, notice: 'Test answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test_answer
      @test_answer = TestAnswer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_answer_params
      params.require(:test_answer).permit(:test, :question, :answer1, :answer2)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    def index

    end

    def contactos
    
    end

    def domino
        
    end
    
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dominos_helper.rb
module DominosHelper
end

app/helpers/test_answers_helper.rb
module TestAnswersHelper
end

app/views/dominos/_form.html.erb
<%= form_with(model: domino, local: true) do |form| %>
  <% if domino.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(domino.errors.count, "error") %> prohibited this domino from being saved:</h2>

      <ul>
      <% domino.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_area :instruction, class:"form-control", placeholder:"Instrucciones:" %>
  </div>

  <div class="form-group">
    <%= form.text_field :question, class:"form-control", placeholder:"Pregunta:" %>
  </div>

  <div class="form-group">
    <%= form.submit "Aceptar", class:"btn btn-success my-2 my-sm-0" %>
    <%= link_to 'Back', dominos_path, class:"btn btn-success my-2 my-sm-0" %>
  </div>

<% end %>

app/views/dominos/edit.html.erb
<br>
<div class="jumbotron">
<h1 class="text-center">Editar Pregunta</h1>


    <div class="form-group">
        <%= render 'form', domino: @domino %>
    </div>

    

</div>

app/views/dominos/index.html.erb
<br>
<p id="notice"><%= notice %></p>
<h1 class="text-center">Test Domino</h1>

<table class="table">
  <thead>
    <tr>
      <th> # </th>
      <th> Instruction </th>
      <th> Question </th>
      <th> Answer1 </th>
      <th> Answer2 </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% i = 0 %>
    <% @dominos.each do |domino| %>
      <tr>
        <td> <%= domino.id %> </td>
        <td> <%= domino.instruction %> </td>
        <td> <%= domino.question %> </td>
        <td> <%=  %> </td>
        <td> <%=  %> </td>
        <td> <%= link_to 'Show', domino %> </td>
        <td> <%= link_to 'Edit', edit_domino_path(domino) %> </td>
        <td> <%= link_to 'Destroy', domino, method: :delete, data: { confirm: "¿Estás seguro?" } %> </td>
      </tr>
      <% i+=1 %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Domino', new_domino_path, class:"btn btn-success my-2 my-sm-0" %>

app/views/dominos/new.html.erb
<br>
<div class="jumbotron">
<h1 class="text-center">New Domino</h1>
    <div class="form-group">
        <%= render 'form', domino: @domino %>
    </div>

    
</div>

app/views/dominos/show.html.erb
<br>
<p id="notice"><%= notice %></p>

<div class="jumbotron">
  <table class="table">
    <tr>
      <td> <p> <strong> Instruction: </strong> <%= @domino.instruction %> </p> </td>

      <td> <p> <strong> Question: </strong> <%= @domino.question %> </p> </td>
      
    </tr>
  </table>
  <br>
  <%= link_to 'Edit', edit_domino_path(@domino), class:"btn btn-success my-2 my-sm-0" %>
  <%= link_to 'Back', dominos_path, class:"btn btn-success my-2 my-sm-0" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeSThree</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <div class="container">
    <div>
      <%= render "partials/header" %>
    </div>

    <div>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </div>
  </body>
</html>

app/views/partials/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <a> <%= link_to (""), root_path%> </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a> <%= link_to "Inicio", root_path, class:"nav-link"%> </a>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
            <a> <%= link_to "Pruebas", welcome_test_path, class:"nav-link" %> </a>
        </li>
        <li class="nav-item">
            <a> <%= link_to "H.E.M.A", root_path, class:"nav-link" %> </a>
        </li>
        <li class="nav-item">
            <a> <%= link_to "Domino", welcome_domino_path, class:"nav-link" %>   </a>
        </li>
        <li class="nav-item">
            <a> <%= link_to "Agregar Test", welcome_test_path, class:"nav-link" %>   </a>
        </li>
        <li class="nav-item">
            <a> <%= link_to "Resultados", root_path, class:"nav-link" %>   </a>
        </li>
        <li class="nav-item">
            <a> <%= link_to "Contactos", welcome_contactos_path, class:"nav-link" %>   </a>
        </li>
        <%= link_to  "Cerrar Sesión", destroy_user_session_path, method: :delete, class:"nav-link" %>
      <% else %>
        <%= link_to  "Iniciar Sesión", new_user_session_path, class:"nav-link" %>
      <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Buscar" aria-label="Search">
      <button class="btn btn-success my-2 my-sm-0" type="submit"> Buscar </button>
    </form>
  </div>
</nav> 

app/views/test_answers/_form.html.erb
<%= form_with(model: test_answer, local: true) do |form| %>
  <% if test_answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(test_answer.errors.count, "error") %> prohibited this test_answer from being saved:</h2>

      <ul>
      <% test_answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :test, class:"form-control", placeholder:"Test:" %>
  </div>

  <div class="form-group">
    <%= form.number_field :question, class:"form-control", placeholder:"Pregunta:" %>
  </div>

  <div class="form-group">
    <%= form.text_field :answer1, class:"form-control", placeholder:"Respuesta 1:" %>
  </div>

  <div class="form-group">
    <%= form.text_field :answer2, class:"form-control", placeholder:"Respuesta 2" %>
  </div>

  <div class="form-group">
    <%= form.submit "Aceptar", class:"btn btn-success my-2 my-sm-0" %>
    <%= link_to 'Back', dominos_path, class:"btn btn-success my-2 my-sm-0" %>
  </div>
<% end %>

app/views/test_answers/edit.html.erb
<h1>Editing Test Answer</h1>

<%= render 'form', test_answer: @test_answer %>

<%= link_to 'Show', @test_answer %> 
<%= link_to 'Back', test_answers_path %>

app/views/test_answers/index.html.erb
<br>

<p id="notice"><%= notice %></p>

<h1 class="text-center">Test Answers</h1>

<table class="table">
  <thead>
    <tr>
      <th>Test</th>
      <th>Question</th>
      <th>Answer1</th>
      <th>Answer2</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @test_answers.each do |test_answer| %>
      <tr>
        <td><%= test_answer.test %></td>
        <td><%= test_answer.question %></td>
        <td><%= test_answer.answer1 %></td>
        <td><%= test_answer.answer2 %></td>
        <td><%= link_to 'Show', test_answer %></td>
        <td><%= link_to 'Edit', edit_test_answer_path(test_answer) %></td>
        <td><%= link_to 'Destroy', test_answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Test Answer', new_test_answer_path, class:"btn btn-success my-2 my-sm-0"  %>

app/views/test_answers/new.html.erb
<br>

<div class="jumbotron">

    <h1 class="text-center">New Test Answer</h1>

    <div class="form-group">
        <%= render 'form', test_answer: @test_answer %>
    </div>

</div>

app/views/test_answers/show.html.erb
<br>
<p id="notice"><%= notice %></p>

<div class="jumbotron">
  <table class="table">
    <tr>
      <td> <p> <strong> Test: </strong> <%= @test_answer.test %> </p> </td>

      <td> <p> <strong>Question:</strong> <%= @test_answer.question %> </p> </td>

      <td> <p> <strong>Answer1:</strong> <%= @test_answer.answer1 %> </p> </td>

      <td> <p> <strong>Answer2:</strong> <%= @test_answer.answer2 %> </p> </td>
    </tr>
  </table>
  <br>
  
  <%= link_to 'Edit', edit_test_answer_path(@test_answer), class:"btn btn-success my-2 my-sm-0" %> 
  <%= link_to 'Back', test_answers_path, class:"btn btn-success my-2 my-sm-0" %>
</div>

app/views/welcome/contactos.html.erb
<h1 class="text-center"> Trabajo Terminal A020 </h1>
<h2 class="text-center"> DeST </h2>
<div class="row justify-content-around">
  <div class="card bg-light mb-3" style="max-width: 20rem;">
    <div class="card-header"> <h2> Director </h2> </div>
    <div class="card-body">
      <h4 class="card-title"> <%= "Alejandro Sigfrido Cifuentes" %> </h4>
      <p class="card-text">
        Lorem ipsum dolor sit amet, idunt ut lom dolore eu pariatur. Excepteur sint, sunt in cborum. 
      </p>
    </div>
  </div>

  <div class="card bg-light mb-3" style="max-width: 20rem;">
    <div class="card-header"> <h2> Director </h2> </div>
    <div class="card-body">
      <h4 class="card-title"> <%= "Emilio" %> </h4>
      <p class="card-text">
        Lorem ipsum dolor sit amet, idunt ut lom dolore eu pariatur. Excepteur sint, sunt in cborum. 
      </p>
    </div>
  </div>

  <div class="card bg-light mb-3" style="max-width: 20rem;">
    <div class="card-header"> <h2> Agradecimientos </h2> </div>
    <div class="card-body">
      <h4 class="card-title"> <%= "" %> </h4>
      <p class="card-text">
        Lorem ipsum dolor sit amet, idunt ut lom dolore eu pariatur. Excepteur sint, sunt in cborum. 
      </p>
    </div>
  </div>

  <div class="card bg-light mb-3" style="max-width: 20rem;">
    <div class="card-header"> <h2> Desarrollador </h2> </div>
    <div class="card-body">
      <h4 class="card-title"> <%= "Andreé Díaz Camacho" %> </h4>
      <p class="card-text">
        Lorem ipsum dolor sit amet, idunt ut lom dolore eu pariatur. Excepteur sint, sunt in cborum. 
      </p>
    </div>
  </div>

  <div class="card bg-light mb-3" style="max-width: 20rem;">
    <div class="card-header"> <h2> Desarrollador </h2> </div>
    <div class="card-body">
      <h4 class="card-title"> <%= "Daniel Serrano" %> </h4>
      <p class="card-text">
        Lorem ipsum dolor sit amet, idunt ut lom dolore eu pariatur. Excepteur sint, sunt in cborum. 
      </p>
    </div>
  </div>
</div>

app/views/welcome/domino.html.erb
<h1> Realizar Test Domino: </h1>
<div class="form-group">
    <%= @dominos.first.instruction %>
</div>
<% @dominos.each do |domino| %>
    <div class="form-group">
        <%= domino.question %>
    </div>
<% end %>

app/views/welcome/index.html.erb
<br>
<div class="jumbotron">
    <h1 class="text-center"> !Bienvenido a DeST¡ </h1>
    <br>
    En esta página encontrarás diferentes test para la obtención de información, la cual, será consultada, 
    analizada y utilizada por psicólogos con la finalidad de reforzar la orientación vocacional dada a los 
    alumnos  de la Escuela Superior de Cómputo (ESCOM).
    Algunos de los test que podrás encontrar son el “Test de Dominó”,  el cual, mide la capacidad mental de 
    resolver problemas de una forma lógica; la prueba HEMA para la valoración general de las actitudes y 
    motivaciones a la hora de enfrentarse al estudio; entre otros.

</div>

app/views/welcome/test.html.erb
<br>
<h1 class="text-center"> Pruebas </h1>
<div>
    <h5> <%= link_to  "Domino", dominos_path %> </h5>
    <h5> <%= link_to  "H.E.M.A" %> </h5>
    <h5> <%= link_to  "Test"%> </h5>   
</div>